spring:
  data:
    mongodb:
      uri: mongodb+srv://dev:4bYvYmuPXaDHMRth@seso-cluster.ftncyzf.mongodb.net/?retryWrites=true&w=majority&appName=seso-cluster
      database: audit_stage

encryption:
  key: SesoAuditKEYSTAGE@####

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/