
name: CI

on:
  push:
    branches: [test]

env:
  REGISTRY: registry.seso.global
  IMAGE_NAME: seso-audit-trail

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test

      - name: Log into Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Tag and push Docker images
        run: |
          docker build -t ${IMAGE_NAME} .
          docker tag ${IMAGE_NAME} ${REGISTRY}/${IMAGE_NAME}:latest
          docker push ${REGISTRY}/${IMAGE_NAME}:latest
          docker tag ${IMAGE_NAME} ${REGISTRY}/${IMAGE_NAME}:${{ github.run_number }}
          docker push ${REGISTRY}/${IMAGE_NAME}:${{ github.run_number }}
